### ISSUE TITLE
Mot de passe perdu

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#138]
Cette fonctionnalité de fonctionne pas sur mon ordinateur mais fonctionne sur l'ordinateur de Gabin Schieffer <br/> Proposé par julie.geffraye@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
Le bug a l'air d'être présent partout désormais, on obtient une erreur 500 dès qu'on clique sur le lien "Mot de passe oublié"
