### ISSUE TITLE
Carte des colocs

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#182]
- [x] Créer les modèles pour les colocs
Le faire hériter de groupe, prévoir que les gens tournent mais pas le bâti
- [x] Formulaire pour créer sa coloc
- [x] Interface pour updater sa coloc
- [x] Carte des colocs
- [ ] Liste des colocs (bâti)

**Comment by unitrium** [comment]
@Sarrus1 @hydrielax @Bromorr  vous voyez d'autres choses ?

**Comment by Sarrus1** [comment]
Une sorte de validation par des admins pour éviter les trolls/spams?

**Comment by unitrium** [comment]
Bonne idée, tu penses mettre la validation à quel niveau ? Pour toute modification ?

**Comment by Sarrus1** [comment]
Je pensais seulement à la création

Je me demande si implementer un système de validation générique, où on peut tout voir depuis une page unique serait plus judicieux. On devra vérifier d'autres choses après de toutes façons non?

**Comment by hydrielax** [comment]
On a rien à vérifier en fait techniquement, juste effectivement faire une relecture avant publication serait bien pour éviter les trolls je pense

**Comment by Sarrus1** [comment]
Oui voila pour eviter les absurditées

**Comment by hydrielax** [comment]
Sinon la liste des collocs c'est pas forcément nécessaire vu qu'il y a déjà la carte, par contre les points plus difficiles ça va être déjà d'adapter le modèle existant pour l'intégrer à la base de données de NP, et aussi pour ajouter ses colocs (l'idéal serait qu'on ajouter directement un lien vers leur page s'ils sont inscrits mais il faut trouver aussi un moyen si un coloc n'est pas sur NP)

**Comment by hydrielax** [comment]
Au passage je vous ais envoyé une invit pour avoir accès au site BDE avec la carte des colocs actuelle, le script est dans views > carte_coloc.hbs, et la base de données dans public > data > appart.json

**Comment by unitrium** [comment]
Bonne idée le système de validation générique, peut-être pas pour tout de suite ? Pour le moment je pense qu'on peut laisser les gens remplir à la main et au pire intervenir après ?
Honnêtement j'ai vu peu de trolls dans mon expérience de DSI BDE

**Comment by unitrium** [comment]
Ça devrait aller pour le modèle en base de données, j'ai une petite idée de ce à quoi cela peut ressembler, je ferais un schéma demain pour vous le montrer

**Comment by Sarrus1** [comment]
Oui c'est sans doute pas prioritaire 👍

**Comment by unitrium** [comment]
Du coup Roomates ne changerait pas l'attribut members donc cela resterait un simple ManyToMany. Je pense pas que ce soit nécéssaire de surcharger members comme pour Liste ou Club parce qu'il n'y a pas besoin de nommer des postes dans une coloc ? On pourrait eventuellement mettre un surnom ? Par exemple mon surnom dans ma coloc c'etait Gordon Ramsay (parce que je cuisinais bien mais c'était un cauchemar en cuisine apres mon passage...)

**Comment by Sarrus1** [comment]
Je pense que ça peut être un petit plus sympa les surnoms des membres de la colloc, et c'est plutôt mineur à implémenter par rapport au reste (sauf si je me trompe).

Pour les années de début, il vaut mieux faire des dates completes non? Je ne sais pas si c'est lié uniquement au Covid mais les colocs changent en cours d'année aussi je crois.

**Comment by hydrielax** [comment]
On peut ajouter des surnoms si vous voulez, ça peut être sympa (mais ça risque de surcharger un peu l'interface, à voir comment on gère). Et pour les années en général ça change en avril à cause des stages mais ça change aussi en septembre parfois, mais je vois pas l'utilité de conserver un historique en fait des précédents locataires donc peut-être pas besoin de dates.

**Comment by unitrium** [comment]
On peut donner un coup d'essai aux surnoms je pense qu'on trouvera une manière de l'afficher sans surcharger.
Ça peut être bien de mettre des dates entières effectivement ça permettra d'établir l'historique plus facilement.

@hydrielax pour te donner un example sympa d'historique:
par exemple sur ma coloc on a réussi à retracer jusqu'à 6 générations de Centraliens qui sont passés par là
lors d'un entretien un gars a regardé l'adresse sur mon CV et m'a dit "Eh mais c'était ma coloc!"
Donc en soit ça apporte pas grand chose mais j'aime bien l'idée de consigner un peu l'histoire de Centrale.
On va peut-être pas garder pour toujours en memoire les gens qui sont passés par la coloc parce que ce sont des données personnelles et qu'il faut les supprimer après un certain temps mais par contre garder une trace du nom de la coloc et de ses dates c'est vraiment sympa.
Par exemple ma coloc change de nom chaque année en fonction de la liste qui l'a

**Comment by hydrielax** [comment]
Ok ton anecdote m'a convaincu 😁

**Comment by unitrium** [comment]
Ça me fait penser note pour plus tard mais les familles de parrainage peuvent etre un truc à ajouter pour septembre (si cela existe encore ?)

**Comment by hydrielax** [comment]
Oui cela existe encore, il y a déjà une page sur ke site BDE qui affiche les familles (il y a juste un affichage à faire), on pourra le mettre sur NP ça serait bien oui

**Comment by unitrium** [comment]
Du coup @hydrielax @Bromorr , @Sarrus1 a commence a implementer la visualization de la carte, je vais m'occuper de faire les modeles a partir de son implementation, je pense qu'un bon exercise pour vous deux serait de mettre en place la detail view d'une coloc dites moi lequel serait partant :)

**Comment by hydrielax** [comment]
On peut pas réutiliser directement le frame du site BDE ? C'est tiré de OpenStreetMap et j'ai l'impression que ce serait assez facile de l'adapter à la base de données non ?

**Comment by Sarrus1** [comment]
> On peut pas réutiliser directement le frame du site BDE ? C'est tiré de OpenStreetMap et j'ai l'impression que ce serait assez facile de l'adapter à la base de données non ?

Au point où on en est, je pense qu'on peut utiliser la notre, [elle ressemble à ça pour le moment](https://i.imgur.com/s4FFutT.png)

**Comment by unitrium** [comment]
Premiere version faite!
