### ISSUE TITLE
Barre de menu reorganisation

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#185]

**Comment by unitrium** [comment]
J'aime bien la repartition, peut-etre rajouter un onglet assos dans l'onglet Clubs & Assos ?

**Comment by hydrielax** [comment]
Dans l'idée pour la page tous les clubs je comptais organiser la page en 4 sections, pour les assos, les clubs BDE, BDA, et BDS... Après on peut séparer les 2 mais je pense que ça sera moins pratique pour le centralien lambda qui recherche un club/assos (les 2 sont souvent confondus)

**Comment by unitrium** [comment]
Done
