### ISSUE TITLE
Passage sous OVH

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#203]
- [x] DB Backup
- [x] Lift and shift instance from AWS to OVH
- [x] S3 Migration
- [x] Maybe replacement of mail sender

**Comment by unitrium** [comment]
Plus que la migration S3 a faire, je ferais cela pendant les vacances.

**Comment by hydrielax** [comment]
Migration vers le S3 terminée par @charles-zablit
