### ISSUE TITLE
Bouton "Quitter un club"

### ISSUE THREAD

**Issue by hydrielax** [nantral-platform/nantralPlatform#219]
Remplacer le bouton "Devenir membre" par "J'ai quitté le club" pour les utilisateurs membres afin de pouvoir les désinscrire. Le bouton indique enregistre alors la date de départ et l'utilisateur reste dans l'historique

**Comment by hydrielax** [comment]
Ce sera d'ailleurs pas mal pour chaque membre qu'il y ait une date d'entrée et une date de sortie, qui par défaut soit celle de quand on s'inscrit sur NP (mais changeable pour ceux qui voudraient indiquer leurs anciens clubs)

**Comment by hydrielax** [comment]
Ajouté la possibilité de quitter le club en re-remplissant le formulaire d'inscription mais avec une date de sortie antérieure à la date d'entrée dans le club. Je sais pas si c'est suffisant ?

**Comment by unitrium** [comment]
Non je pense que le mieux c'est que dans ton profil tu peux retrouver tous tes clubs et que tu puisses les enlever, peut-etre a faire en React pour que ce soit dynamique.

**Comment by hydrielax** [comment]
Si il faut laisser une possibilité explicite je préfère autant que ce soit dans le form de modification du membership, c'est plus logique que de l'avoir sur sa page perso

**Comment by hydrielax** [comment]
Bouton rajouté dans le formulaire d'édition du namedmembership sur la page club du coup !
