### ISSUE TITLE
Problème mise à jour des logos de clubs

### ISSUE THREAD

**Issue by hydrielax** [nantral-platform/nantralPlatform#220]
Le nouveau logo n'apparaît pas quand on change le logo d'un club, parce que ça reste le même nom et donc le navigteur stocke l'ancien logo en cache

**Comment by hydrielax** [comment]
Il y a une astuce pour ça que j'utilisais en php/html c'est de mettre comme url "www.site.fr/image.png?01-01-2021" avec la date de modification du fichier comme ça dès que le fichier est changé ça change la date et l'url et donc le navigateur retélécharge l'image (ça évite de désactiver le cache qui est quand même bien pratique)

**Comment by unitrium** [comment]
Du coup petite explication sur les raisons:
a l'upload je voulais que le fichier remplace toujours l'ancien ainsi tu peux sauvagarde un nombre limite de logos (1 par club) autrement tu pourrais DoS notre serveur en uploadant plein de logos et en faisant discrement exploser notre capacite de stockage. Django quand tu supprimes une image ou la remplace tout ce qu'il fait c'est qu'il efface le lien de sa base de donnees, il ne supprime pas l'image sur le serveur. C'est quelque chose dont on se rend souvent compte que trop tard d'ou ce systeme de remplacement.

**Comment by unitrium** [comment]
Une solution ici serait de modifier Ngnix pour que les images soient mises en cache sur des durees plus courtes.

**Comment by hydrielax** [comment]
Yep je comprends mais ya pas moyen de récupérer la date du fichier en django ? Ça permettrait d'utiliser l'astuce du get et on aurait plus de soucis

**Comment by hydrielax** [comment]
Ou encore plus simple on ajoute juste un champ avec la date de dernière mise à jour dans le modèle group

**Comment by hydrielax** [comment]
Problème résolu avec la dernière méthode !
