### ISSUE TITLE
[Admin Req] Centrale Nantes Etudes - Baptiste PEPIN

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#271]
<a href="http://nantral-platform.fr/group/group/club--centrale-nantes-etudes/admin-request/10/accept">Accepter</a> </br>            <a href="http://nantral-platform.fr/group/group/club--centrale-nantes-etudes/admin-request/10/deny">Refuser</a>

**Comment by hydrielax** [comment]
La modif a été faite manuellement. Les liens ne fonctionnent pas ici car ce sont les anciennes urls en /group et non /club
