### ISSUE TITLE
[Admin Req] Forum Horizons - Sébastien MARECAUX

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#281]
<a href="http://nantral-platform.fr/club/forum-horizons/admin-request/11/accept">Accepter</a> </br>            <a href="http://nantral-platform.fr/club/forum-horizons/admin-request/11/deny">Refuser</a>

**Comment by hydrielax** [comment]
Un bug là aussi, mais pas à cause des urls. Le serveur renvoie une erreur 500 (jambon), donc bug de notre côté. À revérifier

**Comment by hydrielax** [comment]
Je l'ai passé en admin manuellement aussi du coup
