### ISSUE TITLE
rajout d'un lien LinkedIn

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#282]
Hello, en train de remplir la page pour le Forum Horizons, je me rends compte qu'il n'y a pas de catégorie LinkedIn dans les liens qu'on peut rajouter. Je sais que ce n'est pas trop que réseau social qui est très utilisé par les clubs de Centrale, mais je me dis que ça aiderait à mettre en valeur notre compte LI pour le Forum Horizons (et ça pourrait servir aussi pour le FA). <br/> Proposé par sebastien.marecaux@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
LinkedIn ajouté
