### ISSUE TITLE
Recherche dans l'annuaire

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#288]
Si on peut taper un nom et le trouver directement ça peut être bien. Mais au pire c'est dans l'ordre alphabétique donc ça passe, par contre quand y'aura plus de monde, ça sera compliquax <br/> Proposé par Felix.Delattre@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
Même chose pour les clubs si possible ce serait top ;)

**Comment by hydrielax** [comment]
Doublon avec l'issue #199
