### ISSUE TITLE
Modification participation club

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#301]
Hello,
J'ai indiqué que je participais au club équitation et que j'étais l'ancienne Prez, j'ai fait une faute de frappe mais impossible de modifier une fois que c'est validé. 
Ptêtre une idée d'optimisation serait de pouvoir modifier ce qu'on écrit !

Bonnes vacances :) <br/> Proposé par serena.gonzalez@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
Fait
