### ISSUE TITLE
Problème divers

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#308]
Coucou, 

Belle plate-forme d'abord ! C'est top.

Voici qqs questions:

1. Je ne peux pas changer ma photo de profil... Je uploarde, clique sur modification, mais rien se passe. Mais supprimer marche bien.
2. Je ne sais pas comment modifier le rôle dans un club. J'ai fait des erreurs... Et il me semble qu'on ne réussit pas à devenir un membre quand on saisît seulment mm/aa mais pas jj/mm/aa.(parfois on ne sait pas trop le jour d'entrer) et il n'y a pas de remarques pour ce cas.(juste jambon)
3. Pensez-vous on peut y ajouter notre ConseilsX dedans ? Dans la services ou qq part à vous de voir.

Merci déjà pour ce magnifique truc.

Bonne journée et bon courage. <br/> Proposé par Tengfei.Han@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
Premier problème : pb de mise en cache. Corrigé pour tous les fichiers externes (images, pdf) avec un filter tag "file_url",  qui ajouter à l'url la dernière date de modification du fichier pour le recharger dans le cache uniquement quand il est mis à jour

**Comment by hydrielax** [comment]
Deuxième problème : corrigé aussi (ajout d'un affichage lorsque le formulaire est mal rempli + possibilité de modifier le namedmembership après inscription)

**Comment by hydrielax** [comment]
Pour le 3eme il faudrait ajouter des groupes "administration", peut-être une autre app de l'annuaire à voir pour plus tard !

**Comment by unitrium** [comment]
J'en ai discute avec elle via Nantral Platform sur Facebook, elle m'a dit que c'etait pour ajouter des trucs du type Conseil des Etudes et autres. Donc soit on ajoute un modele au dessus de club pour les instances de l'ecole soit on les ajoute simplement en association.

**Comment by hydrielax** [comment]
En fait je pensais créer une nouvelle app pour tous les groupes de contacts "adminsitratif" : CE, CA, Groupe de Travail sur la transition écologique, etc...

**Comment by hydrielax** [comment]
Résolution en cours avec #368

**Comment by hydrielax** [comment]
CX ajoutés ! Je ferme cette issue
