### ISSUE TITLE
Si le lien video n'est pas une video la page du club crash

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#323]
La page du TVCN ne charge plus.
Il semble que ce soit la seule avec ce pb.

**Comment by unitrium** [comment]
Regarder en local ce qu'il se passe.

**Comment by unitrium** [comment]
Resolu pour le TVCN ils avaient mis le lien vers leur chaine dans les liens video au lieu du reseau social.
Il faudrait un failsafe.

**Comment by hydrielax** [comment]
Bug corrigé
