### ISSUE TITLE
[Events & Posts]

### ISSUE THREAD

**Issue by hydrielax** [nantral-platform/nantralPlatform#356]
Les events réservés au membres seulement s'affichent pour tout le monde (ou au moins pour les admins non-membres)

**Comment by hydrielax** [comment]
Les images ne s'uploadent pas

**Comment by unitrium** [comment]
1/ résolu, à condition qu'on arrive à ajouter à nouveau des events

**Comment by hydrielax** [comment]
2/ résolu aussi (il fallait rajouter l'attribut `enctype="multipart/form-data"` à la balise `form` du template pour pouvoir envoyer des fichiers.

**Comment by hydrielax** [comment]
Reste à corriger le problème des 40 caractères pour le titre

**Comment by hydrielax** [comment]
Problème des titres trops longs résolu !
