### ISSUE TITLE
Pimp events et posts

### ISSUE THREAD

**Issue by hydrielax** [nantral-platform/nantralPlatform#382]
- [ ] Afficher les events de la semaine dans un format calendrier sur la page d'accueil
- [ ] Ajouter une page pour afficher tous les events et n'afficher que le calendrier sur la page d'accueil
- [ ] Affichage sous forme de cartes pour être plus joli (en avoir plusieurs par lignes, ne montrer que les 3/4 premières sur les pages des clubs par exemple)
- [ ] Afficher les posts à part (un menu de notification ?)

**Comment by unitrium** [comment]
La couleur du texte des évènements devrait être blanc ou gris pour que le style soit cohérent avec le titre et que le contraste soit agréable à lire. (en vrai si vous trouvez un archi qui s'y connait, les palettes de couleurs c'est tout un monde pas évident du tout) 
Retour CEM

**Comment by hydrielax** [comment]
Doublon avec #742
