### ISSUE TITLE
Version anglaise

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#397]
C'est peut être compliqué/chiant de faire une version anglaise du site mais peut être permettre de switcher sur une page de club d'une version française à la version anglaise serait utile.
En plus, ça permet d'avoir l'onglet "Version anglaise" lorsqu'on modifie une page, se qui motiverait les clubs à la remplir <br/> Proposé par joshua.le-bourhis@eleves.ec-nantes.fr

**Comment by hydrielax** [comment]
Doublon avec #385
