### ISSUE TITLE
Pages lentes

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#415]
Certaines pages sont un peu lentes à charger:
- liste des clubs

C'est peut-être lié au grand nombre d'images, il faudrait étudier la possibilité de cacher ces images.

**Comment by hydrielax** [comment]
Elles sont déjà en cache en fait. La lenteur est dû aux requêtes faites à la BDD et au triage des clubs par asso/clubs BDA/BDE/BDS. J'ai essayé d'améliorer la rapidité en faisant le tri directement sur la BDD plutôt que dans le template (ce qui était fait avant) avec une PR avant-hier, mais c'est pas mieux

**Comment by unitrium** [comment]
Justement je pense faudrait cacher la requete faite à la BDD

**Comment by hydrielax** [comment]
Je sais pas du tout si c'est faisable mais ça serait top effectivement. Après faudra voir comment gérer les mises à jour de la page (clubs qui changent de nom, de logo, ou quand on s'ajoute dans un club)

**Comment by hydrielax** [comment]
Sinon je pensais charger les clubs avec du React, comme ça tu vois les clubs se charger au fur-et-à-mesure et ta page se charge tout de suite, c'est moins énervant pour l'utilisateur (un peu comme facebook en fait)

**Comment by hydrielax** [comment]
Et je me pose la question aussi du fait qu'on envoie une liste de queryset au template, et je me demande si lors de l'envoi au template il extrait tous les champs de la base de données (il convertit les queryset en liste du coup), ou si il fait les sélections dans la BDD après directement dans le template

**Comment by Sarrus1** [comment]
> ou si il fait les sélections dans la BDD après directement dans le template

Normalement c'est ce qui se passe, tout est lazyload au maximum

**Comment by charles-zablit** [comment]
> ou si il fait les sélections dans la BDD après directement dans le template

Normalement c'est ce qui se passe, tout est lazyload au maximum

**Comment by unitrium** [comment]
Actuellement les logos de clubs semblent être tous chargés d'un coup sur la page "Club & assos", ce qui ralentit très fortement l'accès à cette page. Les charger en asynchrone pourrait considérablement améliorer la navigation de ce côté et améliorer l'expérience utilisateur :) 
Retour de CEM

**Comment by hydrielax** [comment]
Petite suggestion sinon est-ce qu'on pourrait pas "compiler" le template html avec la liste des clubs, et en le compléter à chaque fois en faisant juste la requête pour les clubs où on est membre ?

**Comment by hydrielax** [comment]
Il faudrait aussi explorer l'indexation de la BDD pour optimiser le chargement

**Comment by hydrielax** [comment]
Ok j'ai regardé, en fait quand tu charges la page ya que la rubrique "mes clubs" qui est chargée via le react : pour les autres c'et encore chargé via la view (donc ça ralentit la génération de la page). Si c'est pas voulu je pense que c'est du au fait que tu utilises "id=root" pour indiquer au react où se placer dans chaque rubrique mais on ne peut avoir qu'un seul id par page donc il doit ignorer les suivants

**Comment by charles-zablit** [comment]
C'est voulu, je pensais que ce qui prenait le plus de temps c'etait de parcourir tous les membres pour voir si le user etait dedans (mes clubs et assos)
Mais en fait non, c'est plutot rapide...
Je me demande si c'est le moteur de generation du template qui est à la ramasse

**Comment by hydrielax** [comment]
En vrai on a des requêtes beaucoup plus complexes rien que pour les membres et les réseaux sociaux des clubs sur les pages de details, je pense que le problème vient surtout de l'énorme quantité de donnée (mais du coup pourquoi ya une telle différence avec la liste des utilisateurs ? je sais pas ^^)
Je pense qu'il faudra vraiment essayer de générer le template en avance pour ne pas le regénérer à chaque fois, ça sera le plus efficace à mon avis

**Comment by hydrielax** [comment]
Problème définitivement résolu avec la mise en place du cache dans les templates ! 🥳
