### ISSUE TITLE
Redimmensionnement automatique des images

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#419]
Je pense avoir fait crashé le site (déso), en uploadant une image de 1400*1400 pour ma photo de profil. Qd le site est revenu, un tel upload aboutissait désormais sur une erreur 413 Entity too large un truc comme ça. Redimensionnée en 400*400 ça passe nickel par contre. Bref vous connaissez la technique derrière mais voilà l'idée. <br/> Proposé par CEM

**Comment by hydrielax** [comment]
Les images sont déjà redimensionnées automatiquement, l'erreur 413 c'est la limite de taille de fichier défini par le serveur. Est-ce qu'on sait à combien elle est actuellement @charles-zablit @unitrium ? On pourrait peut-être l'augmenter

**Comment by hydrielax** [comment]
Normalement la limite a été relevée
