### ISSUE TITLE
Creer une page note de version

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#423]
Une page en template view qui lit par example le version.md (à ajouter).

**Comment by hydrielax** [comment]
Le système de post est déjà bien pour ça je trouve non ?

**Comment by unitrium** [comment]
Ça pourrait être un bon moyen de retracer l'évolution de Nantral Platform aussi

**Comment by hydrielax** [comment]
Ajouté sur le site de docs: docs.nantral-platform.fr/changelog
