### ISSUE TITLE
Ajouter le cursus Double-Diplôme

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#425]
Un cursus suivi par plus d'un tiers des EI3 qd même. Pour lister les établissements par contre, le challenge est plus grand. <br/> Proposé par CEM

**Comment by hydrielax** [comment]
Est-ce qu'on en profiterait pas pour refaire le site moveon ? En gros une appli DD avec un groupe = une école et un membership avec la formation suivie. Comme ça on a une liste de contacts pour chaque école

**Comment by hydrielax** [comment]
Petite mise au point sur cette issue : on pourrait l'intégrer à l'app "Cours et Formation", avec "DD" ou "SE" comme type et le nom de l'école où on a fait le DD comme nom de la formation. On ajouterait ensuite le nom de la formation suivie dans ce DD/SE au niveau du membre (vu que très peu font le même DD).
Petite difficulté : créer un formulaire pour ajouter son DD/SE (voire une formation en générale) qui soit assez clair pour que les gens ne créent pas un groupe pour chaque master

**Comment by hydrielax** [comment]
Le problème du cursus Double-Diplôme est réglé avec le projet d'app mobilités : #535
