### ISSUE TITLE
raccourci pour les clubs/assos dont on fait parti

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#433]
Salut,
je trouve dommage qu'il faille à chaque fois repasser par l'onglet "Clubs & Assos" et ensuite re-cliquer sur l'asso/club qu'on veut aller modifier (quand on est administrateur), une solution plus pratique pourrait être de rajouter un raccourci dans un menu déroulant dans "Clubs & Assos" pour les clubs dont on est membre/ou alors rendre ça optionnel, avec un petit truc à cocher dans son espace personnel dans la liste des assos dont on est membre ?

Bon courage, et bravo pour tout ce que vous faites ! <br/> Proposé par [cette personne](https://nantral-platform.fr/student/73/)

**Comment by hydrielax** [comment]
Réglé avec le chargement rapide de la page clubs & assos du coup
