### ISSUE TITLE
Pages d'erreur

### ISSUE THREAD

**Issue by hydrielax** [nantral-platform/nantralPlatform#440]
- ajouter une page d'erreur pour l'erreur 403 (accès interdit), quelques uns se sont retrouvés bloqués dessus sans savoir comment revenu à la page d'accueil
- indiquer les codes erreurs sur les pages 404 et 500
- ajouter le jeu du dinosaure (avec un mouton) sur la page 404

**Comment by unitrium** [comment]
Pour le 403, comment est ce qu'ils se sont retrouvés sur une page 403 pour commencer ?
Normalement aucun lien ne devrait t'y mener si tu n'as pas les accès

**Comment by hydrielax** [comment]
Bah c'est le trez du BDE en l'occurence qui est tombé dessus 😅 Je sais pas comment il a fait, peut-être était-ce une ancienne page de son historique sur laquelle il n'avait plus les droits

**Comment by hydrielax** [comment]
Mais comme le genre d'erreur qui peut facilement arriver (par exemple un prez de club qui est admin de la page qui partage le lien d'édition du club avec son respo comm pour le modifier, mais ce dernier n'est pas admin), ça serait bien de mettre une page custom aussi je pense
