### ISSUE TITLE
bug bouton participation à event

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#448]
quand on est sur la page du club organisateur, le bouton de participation à l'évènement auquel on participe reste sous le format "je participe" au lieu de proposer "je ne participe plus"
de plus le clic dessus renvoie sur la page d'accueil du site au lieu de simplement actualiser la participation en restant sur la page du club

sans ça vraiment bravo pour ce site c'est génial ! <br/> <a href='<bound method Student.get_absolute_url of <Student: BURCKARD Emile>>>'Proposé par</a>

**Comment by charles-zablit** [comment]
Si j'ai bien compris le bug, il a été fix dans #471

**Comment by charles-zablit** [comment]
> @unitrium je crois que le nouveau système de signature des suggestions n'est pas encore au point 😅

J'ai caché le nom du coup, et j'ai fix le problème dans #484
