### ISSUE TITLE
demande d'admin sur ma colloc

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#488]
je ne peux pas faire l'envoi de la demande d'admin sur la page de ma colloc "Le Coquillage" <br/> [Clique pour découvrir qui propose ça.](http://nantral-platform.fr/student/84/)

**Comment by charles-zablit** [comment]
Je me suis occupé de la demande en l'ajoutant en admin manuellement.
Apparemment il y a une erreur quand on fait la demande pour devenir admin d'une coloc mais je n'ai pas réussi à le reproduire.

**Comment by charles-zablit** [comment]
Résolu dans #524
