### ISSUE TITLE
Portage de la reservation de la MDE

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#49]
Ce n'est pas vraiment un portage puisque la fonctionalité n'est pas assez complete mais il faudrait pouvoir reserver la mde

https://bdeecn.herokuapp.com/mde

**Comment by hydrielax** [comment]
Du coup le respo MDE actuel est passé sur un google agenda qui leur convient très bien et suffit à leurs besoins. Je pense juste ajouter une page regroupant tous les services des clubs (location de salles, de matériels, etc...) et mettre un lien pour voir le planning en ligne, ça suffira
