### ISSUE TITLE
Disparition des familles de parrainage

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#512]
Il n'est plus possible de trouver les familles de parrainage (ni par fillots, par parrains ou par familles).
J'suis bourré mais j'voulais savoir les fillots de mes potes.
Des bisous. <br/> [Clique pour découvrir qui propose ça.](http://nantral-platform.fr/student/116/)

**Comment by hydrielax** [comment]
Corrigé
