### ISSUE TITLE
Laisser les events quelques heures après qu'ils aient finis

### ISSUE THREAD

**Issue by charles-zablit** [nantral-platform/nantralPlatform#534]
Les events disparaissent du planing dès que l'heure est passée, on pourrait ajouter un petit temps de décalage pour pouvoir le voir un peu plus longtemps.

**Comment by hydrielax** [comment]
Bonne idée ! Je pense il faudrait laisser les clubs mettre une heure de fin, comme ça l'event reste affiché jusqu'à la fin de l'event (pour les retardataires). Et peut-être mettre une page d'events archivés pour retrouver les anciens events

**Comment by charles-zablit** [comment]
Oui ça fonctionnerait bien ça.
En fait une page calendrier ça serait le top

**Comment by hydrielax** [comment]
Nouvelle issue créée pour tous les changements relatifs aux events : #742
