### ISSUE TITLE
bug lien liste des colocs

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#536]
il semblerait qu'il y ait une coloc (l'abattoir) qui soit cachée derrière les titres de la page de la liste des colocs car quand on clique sur les titres des colonnes on tombe sur la page de cette coloc.
Aussi ça pourrait être bien de ranger par ordre alphabétique des nom de colonnes ou alors proposer un autre système de tri car là c'est un peu le foutoir l'ordre (c'est un rangement d'historique ou nord-sud ?)

Bon courage ! <br/> [Clique pour découvrir qui propose ça.](http://nantral-platform.fr/student/73/)

**Comment by hydrielax** [comment]
1. Doublon avec #469
2. Elles ne sont pas triées par défaut mais peuvent être  triées en cliquant sur le titre de la colonne
