### ISSUE TITLE
Mode sombre

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#657]
Hey !
Est-ce que ce serait possible de faire une option mode sombre ? Comme l'arrière plan est très majoritairement blanc, à mon avis ça consomme de l'énergie un peu inutilement d'allumer à fond tout l'écran.
Merci d'avance ! <br/> [Clique pour découvrir qui propose ça.](http://nantral-platform.fr/student/376/)

**Comment by hydrielax** [comment]
Dupilicata avec #426
