### ISSUE TITLE
Replace Webpack with Esbuild and eventually Vite

### ISSUE THREAD

**Issue by charles-zablit** [nantral-platform/nantralPlatform#748]
![Capture](https://user-images.githubusercontent.com/85990211/181113168-c48670e4-0a01-423a-beaf-f3fc4b4b435a.PNG)

Use esbuild instead of Webpack to improve build times.

**Comment by hydrielax** [comment]
I don't know at all esbuild, are our dependencies all compatible with it? For example we strated to use mui for the frontend, but it their documentation only say how to install with webpack

**Comment by charles-zablit** [comment]
Module bundlers do not have compatibility issues with NPM packages, only runtimes (the config differs between a Node.js runtime and a Browser runtime for example).

After some testing, I could not find any error with the scripts bundled with ESBuild.

I have merged the changes in [staging ](https://github.com/nantral-platform/nantralPlatform/tree/staging) with #749.

Here is a preview of the performances benefits during the build on my machine:

**WEBPACK**
![webpack](https://user-images.githubusercontent.com/85990211/181124243-04ef1640-2d68-47dc-8299-c06063401f70.PNG)
**ESBUILD**
![esbuild](https://user-images.githubusercontent.com/85990211/181124247-6c5a56a8-e62c-4428-84c4-36992af296ea.PNG)


The performance gains allowed me to switch the build from Github back to our VPS.

**Comment by charles-zablit** [comment]
> The performance gains allowed me to switch the build from Github back to our VPS.

Nevermind: 9345692bb391f2f2553a5d811423362db4c0f02d
