### ISSUE TITLE
Ajouter un je participe avec option vegetarienne

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#77]
Apres #75 
Ajouter le fait de pouvoir dire son regime

**Comment by hydrielax** [comment]
Il faudrait plutôt laisser les clubs mettre les questions qu'ils souhaitent via un formulaire d'inscription. Pour l'instant on garde l'option d'ajouter un lien vers un google form à la place du bouton "Je participe !" (cf #742), plus tard on pourra voir pour implémenter un système de formulaire
